# Generated by Django 5.1.3 on 2024-11-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flood_relief_center", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aidpackage",
            old_name="type",
            new_name="aid_type",
        ),
    ]
