# Generated by Django 5.1.3 on 2024-11-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_relief_center", "0002_rename_type_aidpackage_aid_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("food and water", "Food and Water"),
                            ("shelter", "Shelter"),
                            ("clothing", "Clothing"),
                            ("medical supplies", "Medical Supplies"),
                            ("medical attention", "Medical Attention"),
                            (
                                "water purification tablets",
                                "Water Purification Tablets",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="donation",
            old_name="type",
            new_name="donation_type",
        ),
        migrations.AlterField(
            model_name="affectedarea",
            name="damageLevel",
            field=models.CharField(
                choices=[
                    ("minor", "Minor"),
                    ("moderate", "Moderate"),
                    ("severe", "Severe"),
                ],
                max_length=8,
            ),
        ),
        migrations.RemoveField(
            model_name="affectedarea",
            name="needs",
        ),
        migrations.RemoveField(
            model_name="victim",
            name="needs",
        ),
        migrations.AddField(
            model_name="affectedarea",
            name="needs",
            field=models.ManyToManyField(to="flood_relief_center.need"),
        ),
        migrations.AddField(
            model_name="victim",
            name="needs",
            field=models.ManyToManyField(to="flood_relief_center.need"),
        ),
    ]
