# Generated by Django 5.1.3 on 2024-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_relief_center", "0004_alter_victim_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="victim",
            name="currentStatus",
            field=models.CharField(
                choices=[
                    ("safe", "Safe"),
                    ("injured", "Injured"),
                    ("missing", "Missing"),
                ],
                max_length=50,
            ),
        ),
    ]
