# Generated by Django 5.1.3 on 2024-11-12 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_relief_center", "0005_alter_victim_currentstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidpackage",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flood_relief_center.reliefcenter",
            ),
        ),
        migrations.AlterField(
            model_name="aidpackage",
            name="victim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flood_relief_center.victim",
            ),
        ),
    ]
