# Generated by Django 5.1.3 on 2024-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_relief_center", "0006_alter_aidpackage_center_alter_aidpackage_victim"),
    ]

    operations = [
        migrations.RenameField(
            model_name="volunteer",
            old_name="skillSet",
            new_name="position",
        ),
        migrations.AlterField(
            model_name="donation",
            name="donation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("money", "Money"),
                    ("supplies", "Supplies"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="availabilityStatus",
            field=models.CharField(
                choices=[("available", "Available"), ("unavailable", "Unavailable")],
                max_length=50,
            ),
        ),
    ]
