# Generated by Django 5.1.3 on 2024-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_relief_center", "0007_rename_skillset_volunteer_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="position",
            field=models.CharField(
                choices=[("staff", "Staff"), ("volunteer", "Volunteer")], max_length=30
            ),
        ),
    ]
