# Generated by Django 5.1.3 on 2024-11-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flood_relief_center", "0008_alter_volunteer_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flood_relief_center.aidpackage",
            ),
        ),
    ]
