# Generated by Django 5.1.3 on 2024-11-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flood_relief_center', '0010_volunteer_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='center',
        ),
    ]
