# Generated by Django 5.1.3 on 2024-11-21 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_relief_center', '0011_remove_volunteer_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flood_relief_center.reliefcenter'),
        ),
    ]
