# Generated by Django 5.1.3 on 2024-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_relief_center', '0012_volunteer_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescueteam',
            name='teamID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
