# Generated by Django 5.1.3 on 2024-11-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_relief_center', '0013_alter_rescueteam_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescueteam',
            name='teamID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
